xcodeproj: HyperwalletUISDK.xcodeproj
scheme: HyperwalletUISDK
ignore:
  - UITests/*
  - Demo/*
  - TransferMethod/Sources/AddTransferMethodSectionData.swift
  - "*/Sources/Resources/*"
  - "*/Sources/Localization/*"
  - "*/Sources/Helper/*"
  - "*/Sources/View/*"
  - "*/Sources/*Controller.swift"
  - "*/Sources/*Cell.swift"
  - "*/Sources/*HyperwalletUI.swift"
  - "*/Sources/Extensions/*"
  - "*/Tests/*"
  - "*/Sources/Helper/*"
