lane :beta do
  version = updateVersion("beta")
  update("beta", version)
end

lane :unit_tests do
  run_tests(
    project: "HyperwalletUISDK.xcodeproj",
    devices: ['iPhone 13 Pro'],
    derived_data_path: './output',
    scheme: "HyperwalletUISDK",
    configuration: 'Debug',
    code_coverage: true,
    xcargs: 'ONLY_ACTIVE_ARCH=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
  )
end

lane :ui_tests do
  run_tests(
    project: "HyperwalletUISDK.xcodeproj",
    devices: ['iPhone 13 Pro Max'],
    scheme: "Demo",
    configuration: 'XCUITest',
    number_of_retries: 3,
    output_remove_retry_attempts: true,
    xcargs: 'ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
  )
end

lane :release_beta do
  version = updateVersion("beta")
  message = "Release #{version}"
  add_git_tag(tag: "#{version}", message: "#{message}")
  set_github_release(tag_name: "#{version}", description: "#{message}")
  push_to_git_remote
  pod_push(allow_warnings: true, skip_tests: true)
end

def updateVersion(type)
  version = last_git_tag
  if type == "beta" then
    version_components = version.split("beta")
    last_component = version_components[-1].to_i + 1
    last_component_string = last_component.to_s
    if last_component_string.size == 1 then
      last_component_string = "0" + last_component_string
    end
    version_components[-1] = last_component_string
    build_version = version_components.join("beta")
  end
end

def update(type, version)
  podspec_name = "HyperwalletUISDK.podspec"
  pod_lib_lint(allow_warnings: true, skip_tests: true)
  version_bump_podspec(version_number: version, path: podspec_name)
  git_add(path: [podspec_name, "*.md"])
  git_commit(path: [podspec_name, "*.md"], message: "Release #{version}")
  push_to_git_remote
end
