name: Update Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  documentation:
    name: Documentation
    strategy:
      matrix:
        include:
          - os: macos-15
            fastlane_task: 'unit_tests'
            xcode_version: 16.2
            code_coverage: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '${{ matrix.xcode_version }}'

      - name: Carthage [Setup cache]
        uses: actions/cache@v3
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}

      - name: Carthage [Install dependencies]
        run: carthage bootstrap
          --platform ios
          --cache-builds
          --use-xcframeworks
          --no-use-binaries

      - name: Run ${{ matrix.task_title }}
        run: fastlane ${{ matrix.fastlane_task }}

      - name: Install sourcekitten
        run: brew install sourcekitten

      - name: Install jazzy 
        run: gem install jazzy

      - name: Extract comment docs
        run: |
          mkdir -p TempJson
            sourcekitten doc --module-name Transfer > TempJson/Transfer.json
            sourcekitten doc --module-name UserRepository > TempJson/UserRepository.json
            sourcekitten doc --module-name TransferRepository > TempJson/TransferRepository.json
            sourcekitten doc --module-name TransferMethodRepository > TempJson/TransferMethodRepository.json
            sourcekitten doc --module-name TransferMethod > TempJson/TransferMethod.json
            sourcekitten doc --module-name Common > TempJson/Common.json
            sourcekitten doc --module-name ReceiptRepository > TempJson/ReceiptRepository.json
            sourcekitten doc --module-name Receipt > TempJson/Receipt.json

      - name: Generate documentation
        run: |
          jazzy \
            --author Hyperwallet Systems Inc \
            --author_url https://www.hyperwallet.com/ \
            --github_url https://github.com/hyperwallet/hyperwallet-ios-ui-sdk \
            --module HyperwalletUISDK \
            --module-version 0.0.1 \
            --hide-documentation-coverage \
            --readme README.md \
            --skip-undocumented \
            --use-safe-filenames \
            --min-acl public \
            --clean \
            --title HyperwalletUISDK \
            --sourcekitten-sourcefile TempJson/Transfer.json,TempJson/UserRepository.json,TempJson/TransferRepository.json,TempJson/TransferMethodRepository.json,TempJson/TransferMethod.json,TempJson/Common.json,TempJson/ReceiptRepository.json,TempJson/Receipt.json \
            --no-hide-documentation-coverage \
            --theme fullwidth \
            --output ./docs \
            --documentation=./*.md

      - name: Publish on GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
